# Site settings
author: James Rogers
title: Turning a Hobby into a Career
header-img: img/home-bg.png
email: jarogers095@gmail.com
copyright_name: James Rogers
description: > # this means to ignore newlines until "baseurl:"
  My journey through Flatiron School's Software Engineering Bootcamp
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jarogers095

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
